### Welcome to My Analytics Server
GET http://localhost:3000/

### Get Number of Sessions for a Specific Site
GET http://localhost:3000/num_sessions/www.s_4.com
# should return 3584

### Get Median Session Length for a Specific Site
GET http://localhost:3000/median_session_len/www.s_4.com
# should return 1361.5

### Get Number of Unique Visited Sites for a Visitor
GET http://localhost:3000/num_unique_visited_sites/visitor_5
# should return 4
